add_executable(hcs301_firmware
    main.c
)

target_link_libraries(hcs301_firmware
    PRIVATE
        err_core
        remote_storage
        button_manager
        led_indicator
        rf_driver
        keeloq_sw
        timer_manager
        pairing_manager
        delete_manager
        cli_service
        power_manager
        device_config
        hcs301_protocol
)